### ISSUE TITLE
VS2017 closes and re-opens when saving a file with VisualLinter active

### ISSUE THREAD

**Issue by icoumans** [jwldnr/VisualLinter#45] opened 2018-05-08 13:44 UTC
### Installed product versions
- Visual Studio: 2017 Professional 15.7.0
- This extension: 1.1.63

### Description
Whenever I try to save a JS file with VisualLinter enabled, VS2017 will close and re-open. The changes are saved, though. This has only started occurring after updating to VS 15.7.0.

### Steps to recreate
1. Open a JS file to edit
2. Ensure VisualLinter is active
3. Make a change to the file
4. Save the file

### Current behavior
After saving the file, VS2017 closes and re-opens.

### Expected behavior
VS2017 should not close at all.

**Comment by jwldnr** [comment] 2018-05-08 13:46
Interesting. I haven’t updated visual studio to the latest version yet, but I’ll have to check it out. Thanks for the report!

**Comment by icoumans** [comment] 2018-05-08 13:52
I should add that I have tried a full re-install and repair install of the Visual Studio instances, and I've ran it in /SafeMode. The problem only occurs again after re-enabling VisualLinter. I'm making an offline installation of VS2017 15.6.7 at the moment, so I will report back tomorrow after I've downgraded my installation to see if the problem disappears.

For anyone else who might be having trouble, and was not aware of being able to downgrade, here's the link:
https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017

**Comment by jwldnr** [comment] 2018-05-08 13:53
Thanks for the additional details. I’ll get on this as soon as I get a chance!

**Comment by jwldnr** [comment] 2018-05-08 15:31
In the meantime if someone finds a (quick) fix for this issue a pull request is always appreciated.

**Comment by oceantume** [comment] 2018-05-08 20:37
Apparently the dependency Newtonsoft.Json 10.0.3 can't be found at runtime. As a temporary fix you can make sure it finds the dll by adding it to the global cache via the gacutil tool or by adding it directly beside VisualLinter.dll in %LocalAppData%\Microsoft\VisualStudio\<Visual Studio version>\Extensions\<VisualLinter ext folder>

**Comment by catcher-in-the-try** [comment] 2018-05-09 04:14
Microsoft has confirmed to me that this issue is caused by VisualLinter. At first I thought it's the problem with Visual Studio 15.7.

**Comment by jwldnr** [comment] 2018-05-09 05:00
It’s definitely related to the extension. I’ll work on a fix ASAP.

**Comment by jwldnr** [comment] 2018-05-09 05:59
This should now be fixed in `v1.1.66`. The new version will soon be available for download.
I'm going to close this issue, however if things don't get better with the new version, post back here and I'll have another go at it.

For reference:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/550ddfdc-027c-41ba-9b32-31e6391bc038/newtonsoftjsondll-not-included-in-vsix?forum=vsx

**Closed by jwldnr** 2018-05-09 05:59 UTC
Labels: bug

**Comment by icoumans** [comment] 2018-05-09 06:06
Thank you very much for the swift fix and workaround.

**Comment by osudude** [comment] 2018-05-09 14:49
Had similar issue.  After upgrading from VS 2017 15.6.4 to VS 2017 15.7.0, Visual Studio would crash upon saving changes to any JS file.  Had no idea it was related so I had to downgrade Visual Studio so that JS saves don't crash the IDE.

**Comment by jwldnr** [comment] 2018-05-09 14:52
@osudude This should be resolved in v1.1.66.
