### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by JWess** [jwldnr/VisualLinter#20] opened 2017-09-25 16:24 UTC
### Installed product versions
- Visual Studio: 2017 Enterprise v15.2
- This extension: Just installed today

### Description
I installed VisualLinter just now, but when I check the Output from VisualLinter, I am greeted by the following error message: 

> Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

My project has a .eslintrc.json file at the solution directory level.

![image](https://user-images.githubusercontent.com/8697891/30819378-8005b4c6-a1ec-11e7-9fbb-b3f581cbbebc.png)

**Comment by jwldnr** [comment] 2017-09-26 05:20
This is, based on my own experience, an annoying bug with Visual Studio (update 2?). Updating to the latest version of Visual Studio (Update 3+) under `Tools > Extensions and Updates... > Updates > Product Updates` should resolve your issue.

However, since this seem to be a recurring issue I am going to revert the line of code causing this error to appear. I will update my comment here once the update is available on the Marketplace.

**Comment by jwldnr** [comment] 2017-09-26 05:24
A new version `1.0.191` will soon be available on the Marketplace.
I will go ahead and close this issue. If updating the extension does not solve the bug, please post back here and I'll reopen the issue.

Thank you for your report!

**Comment by jwldnr** [comment] 2017-09-26 05:39
After a little more digging I found that the version of `Microsoft.VisualStudio.Threading` changed from 15.0.0.0 to 15.3.0.0 in Visual Studio 2017 Update 3. I've added a binding redirect which should help counter this issue.

I'll reopen this issue so please post back here if updating the extension to version `1.0192` or higher does not help.

**Comment by JWess** [comment] 2017-09-26 16:48
I just updated the extension to `1.0192` and restarted Visual Studio, but I seem to be getting the same error. I did not update Visual Studio yet, in case you want to continue to use me as a test bed.

![image](https://user-images.githubusercontent.com/8697891/30872720-0e6a0484-a2b9-11e7-8c59-717dc96b1ad9.png)

![image](https://user-images.githubusercontent.com/8697891/30872702-fc260e26-a2b8-11e7-8730-3aeeae620ede.png)

**Comment by jwldnr** [comment] 2017-09-26 17:57
Well that sucks.

You could help me troubleshoot this by starting with identifying your Visual Studio version.
Install the powershell module from here https://github.com/Microsoft/vssetup.powershell

by opening up powershell and enter `Install-Module VSSetup -Scope CurrentUser`
then proceed by writing `Get-VSSetupInstance`
You should end up with something like this: 
![ps](https://user-images.githubusercontent.com/11960421/30875810-fb3b6632-a2f4-11e7-805f-c0e045acd049.png)

**Comment by jwldnr** [comment] 2017-09-26 18:05
Meanwhile, If you want to get started using this extension the CI build `version 1.0.193` available [here](http://vsixgallery.com/extension/21d9f99b-ec42-4df4-8b16-2a62db5392a5/) should fix the error for you.

Try and manually install this version of the extension and report back here if it fixes the error for you.

**Comment by jwldnr** [comment] 2017-09-27 07:20
This will take some time for me to dig into. I'm able to reproduce this and will attempt to debug in the near future. I've gone ahead and reverted the code change that produce the error.

A new version `1.0.195` will soon be available on the Marketplace that should fix your error. Please post back here once you've updated with the results. Thanks.

**Comment by jwldnr** [comment] 2017-09-28 13:42
After the sync process change the error seem to no longer be present. I'll go ahead and close this issue. 
If you still have this problem post back here and I'll have another look!

**Closed by jwldnr** 2017-09-28 13:42 UTC
Labels: bug
