### ISSUE TITLE
Add support of typescript files (`.ts`)

### ISSUE THREAD

**Issue by ihodev** [jwldnr/VisualLinter#54] opened 2019-04-11 15:06 UTC
ESLint already has support of typescript

**Comment by raix** [comment] 2019-04-11 15:21
Same issue here - would be great if possible to configure extensions eg. js,jsx,ts,tsx
Only javascript is available atm. ref https://github.com/jwldnr/VisualLinter/blob/master/src/VisualLinter/VisualLinterOptions.cs#L47

**Comment by jwldnr** [comment] 2019-04-11 16:19
This should be easy enough to implement, thanks for the suggestion!
Could either of you do me the favor and share a simple Visual Studio project (hosted on github) with the required dependencies in order for this to work (defined in `package.json`) so that I can test/include the information in the documentation.

Thank you in advance.

**Comment by cvs-mrussell** [comment] 2019-05-16 20:36
Hi @jwldnr, I stumbled upon this issue, because I have the same need - to be able to run ESLint within Visual Studio 2017 on Typescript files.

I saw that you had asked that someone provide a sample VS project for testing. Here's a super basic ASP.net MVC project, with a single, simple TS file. There's some information about it in the readme. I hope it can help, or ping me if you need anything further.
https://github.com/cvs-mrussell/TT-ESLint-VisualStudioSample

I'm not very familiar with VS extension development, but if there's anything I can do to help, let me know.

**Comment by jwldnr** [comment] 2019-05-17 05:43
@cvs-mrussell Perfect! Exactly what I requested.
I'll keep you guys updated~

**Comment by jwldnr** [comment] 2019-05-19 07:35
I've looked at implementing this, but found that there's something funky about how the eslint config property `parserOptions.project` is resolved.

From the `@typescript-eslint/eslint-plugin` docs:

![typescript](https://user-images.githubusercontent.com/11960421/57978901-c173bb80-7a15-11e9-8123-d9686b925cd6.png)

Here's the problem:
When the `VisualLinter` linting process is run-- but has a different working directory compared to where the eslint config file (e.g. `.eslintrc.js`) is located, then the `parserOptions.project` path will resolve relative to the working directory of the process being run.

Here's an example using the provided repository by @cvs-mrussell:

1. I have a terminal with my user folder as working directory (e.g. `C:\Users\m41n`)
2. I run the linting process through the terminal on a file located in different directory:
    ` $ C:\Users\m41n\Source\Repos\TT-ESLint-VisualStudioSample\src\TypeScriptSample\node_modules\.bin\eslint.cmd "C:\Users\m41n\Source\Repos\TT-ESLint-VisualStudioSample\src\TypeScriptSample\Scripts\app\HomePageService.ts" --format="json"`

**By omitting** the `--config` parameter to the CLI, the config will be resolved correctly by eslint. In this case:
`C:\Users\m41n\Source\Repos\TT-ESLint-VisualStudioSample\src\TypeScriptSample\.eslintrc.js` 

Here's the content of the `.eslintrc.js` file (irrelevant parts omitted for brevity):

```
module.exports = {
    ...
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "./tsconfig.json"
    },
    ...
```

I'll get an parsing error, saying that the file `C:\\Users\\m41n\\tsconfig.json` could not be found (`parserOptions.project` path is relative to the working directory of the process being run, rather than the `.eslintrc.js` file):

```[
  {
    "filePath": "C:\\Users\\m41n\\Source\\Repos\\TT-ESLint-VisualStudioSample\\src\\TypeScriptSample\\Scripts\\app\\HomePageService.ts",
    "messages": [
      {
        "ruleId": null,
        "fatal": true,
        "severity": 2,
        "message": "Parsing error: File 'C:\\Users\\m41n\\tsconfig.json' not found."
      }
    ],
    "errorCount": 1,
    "warningCount": 0,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "source": "..."
  }
]``` 

This is a minor inconvenience and I could fix this by manually resolving the `tsconfig.json` path within the extension, but I'd rather ask if this is the intended behavior before hacking around it.
I'll open an issue in the `@typescript-eslint` repository and update this issue with the progress.

**Comment by jwldnr** [comment] 2019-05-19 18:57
I've received an reply from the @typescript-eslint devs and I'll have to make adjustments to the underlying code before releasing this in a new version.

Sidenote: I totally overlooked the `tsconfigRootDir` property..

**Comment by cvs-mrussell** [comment] 2019-05-20 13:10
Thanks for the detailed updates, I really appreciate you looking into this. If I can help with testing or anything, let me know.

**Comment by jwldnr** [comment] 2019-05-25 08:23
I've added TypeScript support in #55.
A new version of VisualLinter will soon be available on the Marketplace. Please upgrade your extension and open a new issue if you find any bugs~

Thanks for the help @cvs-mrussell!

**Closed by jwldnr** 2019-05-25 08:23 UTC
Labels: enhancement, help wanted
