### ISSUE TITLE
Exception in Plugin Whilst Navigating Javascript File

### ISSUE THREAD

**Issue by danspam** [jwldnr/VisualLinter#1] opened 2017-07-19 04:38 UTC
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 1.0.79

### Description
The following error occurred when navigating around a javascript file:

`System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary2.TryRemove(TKey key, TValue& value)
   at Microsoft.VisualStudio.JSON.Package.ErrorSources.JSONTableDataSink.RemoveFactory(ITableEntriesSnapshotFactory oldFactory)
   at Microsoft.VisualStudio.JSON.Package.ErrorSources.JSONTableDataSink.FactorySnapshotChanged(ITableEntriesSnapshotFactory factory)
   at jwldnr.VisualLinter.Tagging.TaggerProvider.UpdateAllSinks() in C:\projects\visuallinter\VisualLinter\Tagging\TaggerProvider.cs:line 157
   at jwldnr.VisualLinter.Tagging.Tagger.SnapToNewSnapshot(LinterSnapshot snapshot) in C:\projects\visuallinter\VisualLinter\Tagging\Tagger.cs:line 208
   at jwldnr.VisualLinter.Tagging.Tagger.OnBufferChange(Object sender, TextContentChangedEventArgs e) in C:\projects\visuallinter\VisualLinter\Tagging\Tagger.cs:line 188
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler1 eventHandlers, TArgs args)`

### Steps to recreate
Sorry, I couldn't recreate it. It has occurred a couple of times since using the plugin but I am yet to discover under what circumstances. Thought I would log it anyway in case there is a defensive fix that can be deduced from the exception.

**Comment by jwldnr** [comment] 2017-07-24 06:17
Thank you for the report.
This exception is new to me, but I'll see if I can reproduce this on my side. I'll report back here with my findings.

**Comment by jwldnr** [comment] 2017-07-24 09:42
I am unable to reproduce- however I've changed the code to not update all the sinks by passing null to FactorySnapshotChanged.

I am closing this as a a new version (1.0.86) will soon be available on the Marketplace. 
If updating wont solve your problem, post back here and I'll reopen this issue.

**Closed** 2017-07-24 09:43 UTC
Labels: Unable to Reproduce
